# Generated by Django 5.0.3 on 2024-03-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='color',
            field=models.CharField(choices=[('BL', 'Blue'), ('GN', 'Green'), ('GY', 'Grey'), ('PI', 'Pink'), ('RE', 'Red'), ('BE', 'Beige'), ('MC', 'Multicolor'), ('WH', 'White'), ('BA', 'Black'), ('BR', 'Brown'), ('SL', 'Silver'), ('GO', 'Gold'), ('PU', 'Purple')], default='Multicolor', max_length=100),
        ),
    ]
