# Generated by Django 5.0.3 on 2024-03-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_item_amount_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_of_item',
            field=models.ImageField(default='ERP/dashboard/static/dashboard/images/default.jpg', upload_to='ERP/dashboard/static/dashboard/images'),
        ),
    ]
