# Generated by Django 5.0.3 on 2024-03-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_item_image_of_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_of_item',
            field=models.ImageField(default='ERP/dashboard/product_images/default.jpg', upload_to='ERP/dashboard/product_images'),
        ),
    ]
