# Generated by Django 5.0.3 on 2024-03-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_item_image_of_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_of_item',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='ERP/dashboard/product_images/default.jpg', upload_to='ERP/'),
        ),
    ]
