# Generated by Django 5.0.3 on 2024-03-31 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='instock',
        ),
    ]
