# Generated by Django 5.0.3 on 2024-04-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
    ]
